name: âš¡ï¸ Update Status. âš¡ï¸
on:
  schedule:
      - cron: "0 */3 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ Set up Python 3.9 ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: ğŸŒ€ Clone the Repo ğŸŒ€
        uses: actions/checkout@master
        with:
          repository: PAINBOI2008/BotStatus
      - name: ğŸ“€ Install dependency. ğŸ“€
        run: |
          pip install pytz telethon pygithub
          pip install --upgrade pip
      - name: ğŸƒâ€â™‚ï¸ run the bot. ğŸƒâ€â™‚ï¸
        run: |
          python3 bot.py
        env:
          REPO: ${{ secrets.REPO }}
          SESSION: ${{ secrets.SESSION }}
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TOKEN: ${{ secrets.TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}
